### ISSUE TITLE
각 목적지를 선택할수있는 스피닝 버튼을 지도 위에 구현

### ISSUE THREAD

**Issue by kimseungdeok** [NPC-Team/NPC_project#11]

**Comment by Austinia** [comment]
현재 스피닝 팝업창까지 구현

**Comment by Austinia** [comment]
대학 건물 리스트까지 푸시했음, 누락된 대학건물 발견하면 코멘트 바람

**Comment by kimseungdeok** [comment]
평생교육원, 아라컨벤션홀,중앙 디지털 도서관, 의학전문대학원 빠져있습니다. 외국어교육원->언어교육원 수정해야합니다.

**Comment by kimseungdeok** [comment]
평생교육원, 아라컨벤션홀,중앙 디지털 도서관, 의학전문대학원 추가 완료. 외국어교육원->언어교육원 수정 완료

**Comment by Austinia** [comment]
각 건물별 좌표 리스트 따로 작성함 새로 추가된 건물의 좌표를 마저 입력 필요, 팝업창 스피너에 선택된 장소 및 좌표값이 맵 액티비티로 이동하는 것 구현 토스트 메세지로 확인 가능

**Comment by kimseungdeok** [comment]
추가된 건물의 좌표 입력 완료
