### ISSUE TITLE
profile 버튼 만들기

### ISSUE THREAD

**Issue by kimseungdeok** [NPC-Team/NPC_project#20]
- [x] 도보, 자전거, 자동차 버튼 생성

**Comment by Austinia** [comment]
class에 프로파일 객체 생성 완료, 레이아웃 완성 후 연결예정

**Comment by Austinia** [comment]
레이아웃 라디오 버튼 형식으로 완성, 기존 맵 액티비티 토스트텍스트에 추가함.

**Comment by Yurang4** [comment]
도보 -> routed-foot
자동차-> routed-car
자전거 -> routed-bike

**Comment by Austinia** [comment]
Map_activity.java 293라인에서 스트링 객체로 받게 해두었음
