### ISSUE TITLE
기능별로 클래스 나누기

### ISSUE THREAD

**Issue by kimseungdeok** [NPC-Team/NPC_project#22]

**Comment by Austinia** [comment]
현재 맵 액티비티에서 디자인팀이 만든 클래스, 변수 앞마다 주석 삽입 완료

**Comment by kimseungdeok** [comment]
현재 Map_activity에서 지도를 화면에 표시해주는 부분, 메뉴 부분을 다른 클래스로 만들어 나누어야할것같습니다.
