### ISSUE TITLE
장소별 오버레이 표시

### ISSUE THREAD

**Issue by Yurang4** [NPC-Team/NPC_project#28]
- [x] 건물별 위치 및 정보 정리
- [x] 건물별 오버레이 찍기
- [x] 오버레이 클릭 시 해당 건물의 간단한 정보 및 표시
- [x] 자세히보기로 건물의 자세한 정보를 표시하는 창 띄우기
- [ ] 해당 건물까지의 경로 안내를 보여주는 버튼 만들기

**Comment by Kimkyeongbeom4844** [comment]
건물 및 좌표 csv 파일 커밋
