### ISSUE TITLE
중간 발표 ppt 제작

### ISSUE THREAD

**Issue by Yurang4** [NPC-Team/NPC_project#3]

**Comment by kimseungdeok** [comment]
ppt 초안 확인 부탁드립니다.

https://drive.google.com/file/d/1eF82fQ-An_pkE2DCsoJRngpwH12n6dH_/view?usp=sharing
https://drive.google.com/file/d/1gM5mpS_nEErJx1gdD4Lb78szfr7kr_jF/view?usp=sharing

첫번째 링크가 좀 다듬어진 ppt이고
두번째 링크는 덜 다듬어진 ppt 입니다.
